apiVersion: v1
kind: Secret
metadata:
  name: spotme-secrets-replica
  namespace: spotme
type: Opaque
stringData:
  # certs/05-claves-mysql-replica/server-replica-certs.pem
  DB_SSL_CERT: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----


  # certs/05-claves-mysql-replica/server-replica-key.pem
  DB_SSL_KEY: |
    -----BEGIN PRIVATE KEY-----

    -----END PRIVATE KEY-----

  # certs/05-claves-mysql-replica/ca-cert.pem
  DB_SSL_CA: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
