apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: spotme
type: kubernetes.io/tls
stringData:

  # TLS Certificates CloudFlare certs/09-loadbalancer-cloudflare
  tls.crt: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN PRIVATE KEY-----

    -----END PRIVATE KEY-----
